(function(){
 'use strict';
 const api=window.PainmapAccount,root=document.getElementById('personalApp');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=v=>new Date(v).toLocaleString('zh-CN');
 const registrationEnabled=window.HOOPFOOT_DATA_CONFIG?.personalRegistrationEnabled===true;
 let viewVersion=0,records=[],recovery=location.hash.includes('type=recovery');
 const labels={language:'填写语言',primary_location:'疼痛区域',secondary_location:'具体位置',pain_shape:'疼痛范围',pain_depth:'疼痛深浅',vas:'疼痛评分（0–10）',onset_event:'发生方式',rf_none:'没有／不确定有紧急情况',rf_circulation:'发冷、发白、发青或大量出血',rf_systemic:'发热寒战伴红肿热痛',foot_side:'左／右脚',location_view:'定位视角'};
 for(const q of [...ACUTE_QUESTIONS,...CHRONIC_QUESTIONS,...ADDITIONAL_QUESTIONS,...YESNO_QUESTIONS,...FUNCTIONAL_TESTS])labels[q.field]=q.title||q.label||q.field;
 for(const q of REDFLAG_OPTIONS)labels[q.id]=q.label;
 for(const q of window.PainmapTriage?.questions||[])labels[q.field]=q.zh;
 const technicalFields=new Set(['safety_triage','location_input','location_model_version','location_view','safety_summary_only']);
 const questionOptions=Object.fromEntries([...ACUTE_QUESTIONS,...CHRONIC_QUESTIONS,...ADDITIONAL_QUESTIONS,...YESNO_QUESTIONS,...FUNCTIONAL_TESTS,...(window.PainmapTriage?.questions||[])].map(q=>[q.field,q.options||[]]));
 const answerText=(k,v)=>{const opts=questionOptions[k]||[];const one=x=>{const o=opts.find(o=>o.v===x);return o?.label||o?.zh||value(x);};return Array.isArray(v)?v.map(one).join('、'):one(v);};
 const value=v=>v===true?'是':v===false?'否':Array.isArray(v)?v.map(value).join('、'):v&&typeof v==='object'?Object.entries(v).map(([k,x])=>`${labels[k]||k}：${value(x)}`).join('；'):({right:'右脚',left:'左脚',positive:'阳性',negative:'阴性',untested:'未测试',yes:'有',no:'没有／不确定',acute:'急性',chronic:'慢性',unknown:'不确定',zh:'中文',en:'英文'}[v]||String(v??'—'));
 const title=r=>r.outcome==='emergency_stop'?'安全排查：建议就医':r.snapshot.ranking?.[0]?.nameZh||'暂无明确匹配结果';
 const notice=text=>{const el=document.getElementById('personalMessage');if(el)el.textContent=text;};
 function auth(register=false){
 viewVersion++;
 root.innerHTML=`<div class="personal-auth"><p class="eyebrow">MY PAINMAP</p><h1>${recovery?'设置新密码':register?'创建个人账户':'欢迎回来'}</h1>${!registrationEnabled?'<p class="personal-badge">个人中心内测 · 公开注册待开放</p>':''}<p class="personal-muted">登录后，查看每一次筛查的答案和结果，持续记录同一次伤病的变化。</p><form id="authForm" class="personal-card">${recovery?'':'<label>邮箱<input id="email" type="email" autocomplete="email" required></label>'}<label>密码<input id="password" type="password" autocomplete="${register||recovery?'new-password':'current-password'}" minlength="8" required></label>${register?'<label><input id="personalConsent" type="checkbox" required> 我同意将筛查答案和结果保存到个人账户，用于查看历史记录。这与匿名研究授权分开。</label>':''}<button class="btn btn-primary" type="submit">${recovery?'更新密码':register?'注册':'登录'}</button><p id="personalMessage" class="personal-message" role="status"></p></form>${recovery?'':`<div class="personal-actions"><button class="btn btn-secondary" id="switchAuth">${register?'已有账户，登录':'没有账户，注册'}</button><button class="btn btn-secondary" id="forgot">忘记密码</button></div>`}<p><a href="./index.html">先以访客身份筛查 →</a></p></div>`;
 document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;notice('正在处理…');try{const password=document.getElementById('password').value;let res;if(recovery){res=await api.db.auth.updateUser({password});}else{const email=document.getElementById('email').value.trim();res=register?await api.db.auth.signUp({email,password,options:{emailRedirectTo:new URL('account.html',location.href).href}}):await api.db.auth.signInWithPassword({email,password});}if(res.error)throw res.error;if(recovery){recovery=false;history.replaceState(null,'',location.pathname);await dashboard();}else if(register&&!res.data.session){notice('请查收验证邮件并完成验证，再返回登录。如果已注册，请直接登录或重置密码。');}else{await api.init();await dashboard();}}catch(err){notice('未能完成：'+err.message);}finally{button.disabled=false;}};
 if(!recovery){document.getElementById('switchAuth').onclick=()=>{if(!registrationEnabled){notice('个人账户正在内测，公开注册尚未开放。验证邮件服务接通后即可注册；目前仍可使用访客筛查。');return;}auth(!register);};document.getElementById('forgot').onclick=async()=>{if(!registrationEnabled){notice('密码重置邮件服务尚未开放，请联系项目负责人协助处理。');return;}const email=document.getElementById('email');if(!email.reportValidity())return;notice('正在发送重置邮件…');const {error}=await api.db.auth.resetPasswordForEmail(email.value.trim(),{redirectTo:new URL('account.html',location.href).href});notice(error?'发送失败：'+error.message:'如该邮箱已注册，你会收到重置密码邮件。');};}
 }
 async function dashboard(){
 if(!api.user)return auth();
 const ownerId=api.user.id,loadVersion=++viewVersion;
 root.innerHTML='<p>正在读取你的记录…</p>';
 try{const loaded=await api.list();if(loadVersion!==viewVersion||api.user?.id!==ownerId)return;records=loaded;}catch(err){if(loadVersion!==viewVersion||api.user?.id!==ownerId)return;root.innerHTML=`<h1>我的 Painmap</h1><p>个人记录暂时无法读取，请稍后重试。</p><p class="personal-message">${esc(err.message)}</p><button id="retry" class="btn btn-primary">重试</button><button id="logout" class="btn btn-secondary">退出登录</button>`;document.getElementById('retry').onclick=dashboard;bindLogout();return;}
 const complete=records.some(r=>r.outcome==='completed'||r.outcome==='no_candidate'),latest=records[0];
 let draft=false;try{const saved=JSON.parse(localStorage.getItem(api.draftKey())||'null')?.data;draft=!!saved?._latestStep&&!saved?._personalSaved;}catch(_){}
 root.innerHTML=`<p class="eyebrow">MY PAINMAP</p><h1>你的每一步，都有记录</h1><p class="personal-muted">${esc(api.user.email)} · ${records.length} 次筛查</p><label for="recordLabel">新记录名称（可选）</label><input id="recordLabel" maxlength="60" placeholder="例如：左脚踝 · 训练后不适" style="padding:12px;border:1px solid #b7bcc4;border-radius:8px;width:min(100%,360px);display:block;margin-top:8px"><div class="personal-actions"><button id="newScreen" class="btn btn-primary">＋ 全新筛查</button>${draft?'<a class="btn btn-secondary" href="./index.html">继续本设备的草稿</a>':''}<a class="btn btn-secondary" href="#rehab">我的康复</a><button id="logout" class="btn btn-secondary">退出登录</button></div><div class="personal-grid"><section><h2>我的筛查记录</h2>${records.length?records.map(r=>`<article class="personal-card"><span class="personal-badge">${r.source_id?'复查更新':'首次记录'} · ${esc(value(r.snapshot.mode))}</span><h3>${esc(r.snapshot.recordLabel||title(r))}</h3>${r.snapshot.recordLabel?`<p>${esc(title(r))}</p>`:''}<p class="personal-muted">${date(r.created_at)}<br>${esc([r.snapshot.answers?.primary_location,r.snapshot.answers?.secondary_location].filter(Boolean).join(' · '))}</p><div class="personal-actions"><button class="btn btn-secondary" data-detail="${r.id}">查看结果和答案</button><button class="btn btn-secondary" data-copy="${r.id}">基于这次更新</button></div></article>`).join(''):'<div class="personal-card personal-empty">还没有记录。完成第一次筛查后，答案和结果会出现在这里。</div>'}</section><aside><section class="personal-card" id="rehab"><span class="personal-badge">${complete?'已完成筛查':'先建立筛查记录'}</span><h2>康复与护理</h2><p class="personal-muted">赛前准备、赛后恢复与日常足踝训练。教程可浏览，具体动作仍需确认适用条件。</p>${latest?.outcome==='emergency_stop'?'<p>最近一次筛查提示需要医疗评估，请先就医，不自行训练。</p>':''}<div class="personal-actions"><a class="btn btn-primary" href="care.html#rehab">浏览康复模块</a><a class="btn btn-secondary" href="care.html#emergency">紧急处理</a></div><p class="personal-muted">目前不会根据筛查结果自动开具训练方案。</p></section><section class="personal-card"><h3>复查如何保存？</h3><p class="personal-muted">“基于这次更新”会带入原答案。请核对每一题，尤其是当前安全情况。提交后新增记录，原记录保持不变。</p></section></aside></div>`;
 document.getElementById('newScreen').onclick=()=>api.start(null,document.getElementById('recordLabel').value.trim());bindLogout();
 root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(records.find(r=>r.id===b.dataset.detail)));
 root.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>api.start(records.find(r=>r.id===b.dataset.copy)));
 }
 function bindLogout(){document.getElementById('logout').onclick=async()=>{const {error}=await api.db.auth.signOut({scope:'local'});if(error){alert('退出失败，请重试');return;}records=[];auth();};}
 function detail(r){
 const s=r.snapshot;root.innerHTML=`<button id="back" class="btn btn-secondary">← 我的记录</button><h1>${esc(r.snapshot.recordLabel||title(r))}</h1><p class="personal-muted">${date(r.created_at)} · 此次提交的原始记录</p><section class="personal-card"><h2>筛查结果</h2><p>筛查提示不构成医学诊断。评分是规则匹配分数，不是患病概率。</p>${s.emergency?'<p>此次筛查因安全风险停止，请按照当时页面的提示接受医疗评估。</p>':s.ranking?.length?`<ol>${s.ranking.map(x=>`<li>${esc(x.nameZh||x.nameEn||x.key)} · ${esc(x.score)} 分</li>`).join('')}</ol>`:'<p>没有达到输出门槛的结果，并不代表没有伤病。</p>'}</section><section class="personal-card"><details><summary>查看当时的完整报告</summary><p style="white-space:pre-wrap">${esc(s.reportText||'这份记录没有保存完整报告文字。')}</p></details></section><section class="personal-card"><h2>当时的全部选择</h2>${r.source_id&&s.emergency?'<p class="personal-muted">本次在安全排查阶段停止，下面的其他症状答案可能由上次带入，尚未在本次重新核对。</p>':''}<table class="personal-table"><tbody>${Object.entries(s.answers||{}).filter(([k])=>!technicalFields.has(k)).map(([k,v])=>`<tr><th scope="row">${esc(labels[k]||k)}</th><td>${esc(answerText(k,v))}</td></tr>`).join('')}</tbody></table><details><summary>特殊测试选择</summary><p>${esc(value(s.testResults||{}))||'未填写'}</p></details></section><div class="personal-actions"><button id="copyRecord" class="btn btn-primary">基于这次记录更新</button></div><p class="personal-muted">将生成新记录，不会修改本次结果。</p>`;
 document.getElementById('back').onclick=dashboard;document.getElementById('copyRecord').onclick=()=>api.start(r);window.scrollTo(0,0);
 }
 api.db?.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){recovery=true;auth();}});
 api.init().then(()=>recovery?auth():dashboard()).catch(()=>{root.textContent='账户服务未能连接，请刷新重试。';});
 window.addEventListener('painmap-account-change',()=>{if(!api.user){records=[];auth();}});
})();
