(function(){
'use strict';
const {items,groups}=window.PainmapCareData,root=document.getElementById('careApp');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let entries=[],timer=null,ticker=null,guard=false,quick={},urgent={},lastPath='home';
const link=(href,title,sub='',tag='')=>`<a class="tile" href="#${href}"><span><strong>${esc(title)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</span>${tag?`<em>${esc(tag)}</em>`:''}<span aria-hidden="true">↗</span></a>`;
const note=(s,red=false)=>`<div class="notice ${red?'danger':''}">${esc(s)}</div>`;
const back=(to,label)=>`<a class="back" href="#${to}">← ${esc(label)}</a>`;
const heading=(title,sub)=>`<h1>${esc(title)}</h1><p class="lede">${esc(sub)}</p>`;
function stopTimer(){clearInterval(ticker);ticker=null;timer=null;}
function route(){
 stopTimer(); const bits=(location.hash.slice(1)||'home').split('/');lastPath=bits.join('/');
 const [page,id,parent]=bits;
 if(page==='home')root.innerHTML=`<p class="eyebrow">YOUR NEXT STEP</p>${heading('今天，你需要什么？','选择当下需要的支持。')}<div class="entry-grid">${link('rehab','康复模块','赛前准备 · 赛后恢复 · 日常训练')}${link('emergency','紧急处理','刚受伤？先停止运动并检查紧急情况','优先安全')}</div><p class="quiet">护理教程不代替诊断或上场评估。</p>`;
 else if(page==='rehab')root.innerHTML=back('home','首页')+heading('康复模块','按场景选择，按需要练习。')+`<div class="stack">${link('pre','比赛／训练前','热敷 · 活动度 · 激活 · 贴扎','01')}${link('post','训练后短暂恢复','软组织放松 · 热敷 · 冷敷','02')}${link('gym','健身房训练','力量 · 平衡 · 足弓 · 弹性','03')}</div>`+note('当前为教程浏览，不代表已根据筛查确认适合你。具体训练须遵守已有专业限制。');
 else if(groups[page])renderGroup(page);
 else if(page==='action'&&items[id]&&groups[parent])renderAction(id,parent);
 else if(page==='urgent')renderUrgent();
 else if(page==='quick')renderQuick();
 else if(page==='history')root.innerHTML=back('home','首页')+heading('本次练习反馈','仅保留在当前打开的页面中，刷新后清空；未同步到账户。')+(entries.length?entries.slice().reverse().map(e=>`<div class="tile"><span><strong>${esc(e.title)}</strong><small>${esc(e.time)} · ${esc(e.feedback)}</small></span></div>`).join(''):note('暂时没有反馈。打开动作后可记录感受。'));
 else root.innerHTML=back('home','首页')+heading('没有找到这个页面','请返回选择内容。');
 bind();window.scrollTo(0,0);root.focus({preventScroll:true});
}
function renderGroup(key){const g=groups[key];root.innerHTML=back(key==='emergency'?'home':'rehab',key==='emergency'?'首页':'康复模块')+heading(g.title,g.sub)+(key==='emergency'?`${note('有危险表现时立即求助，不要等做完护理。',true)}${link('urgent','先检查紧急情况','按已经观察到的情况回答','优先')}`:key==='pre'?link('quick','快速伤处检查','新发红、淤青或肿胀增加？'):note(key==='gym'?'按当前能力选择。高级动作需专业指导，不自动升级。':'出现新伤或明显加重，请先进入紧急处理。'))+g.groups.map(([name,ids])=>`<section><h2>${esc(name)}</h2><div class="cards">${ids.map(id=>link('action/'+id+'/'+key,items[id].title,items[id].sub,items[id].restricted?'需指导':'')).join('')}</div></section>`).join('')+(key!=='emergency'?'<a class="textlink" href="#emergency">刚受伤或症状加重？查看紧急处理 →</a>':'');}
const calfVersions=[
 {label:'负重单脚',title:'负重单脚提踵',equip:'固定扶手 · 哑铃（按方案）',dose:'负重和次数按已有个人方案。',steps:['一手轻扶固定物，另一手持哑铃，训练侧单脚站稳。','保持前脚掌接地，缓慢抬起脚跟，再有控制地落回地面。','身体保持直立，不弹起借力；无法稳定完成时减少负重或选择自重版本。']},
 {label:'自重单脚',title:'自重单脚提踵',equip:'固定扶手',dose:'可先1组8–10次，以稳定完成为前提。',steps:['一手轻扶固定物，训练侧单脚承重，另一脚离地，不拿哑铃。','缓慢抬起支撑脚的脚跟，再有控制地放回地面。','前脚掌保持稳定，不向内外翻倒；无法稳定完成时改为双脚。']},
 {label:'双脚',title:'双脚提踵',equip:'固定扶手',dose:'可先1组8–10次，以稳定完成为前提。',steps:['双脚自然分开站立，双手轻扶固定物，两脚共同承重。','保持两侧前脚掌接地，同时缓慢抬起脚跟。','再将两侧脚跟缓慢落地，重量均匀分配，不弹起或偏向一侧。']}
];
let calfVersion=0;
function renderAction(id,parent){const a=id==='calf'?{...items[id],...calfVersions[calfVersion]}:items[id];root.innerHTML=back(parent,groups[parent].title)+heading(a.title,a.sub)+`${id==='calf'?`<div class="feedback-row" role="group" aria-label="选择提踵版本">${calfVersions.map((v,i)=>`<button data-calf-version="${i}" aria-pressed="${i===calfVersion}" style="${i===calfVersion?'background:#fff2e9;border-color:#c65315;color:#a44113;':''}">${esc(v.label)}</button>`).join('')}</div><p class="quiet">选择已确认适合的版本，查看对应教程。</p>`:''}<div class="media" aria-label="${esc(a.title)}教程占位"><span class="media-label">动作教程</span><strong>${esc(a.title)}</strong><small>视频准备中 · 先查看文字步骤</small></div><div class="meta"><span>用品</span><strong>${esc(a.equip)}</strong></div>${a.dose?`<div class="meta"><span>用量</span><strong>${esc(a.dose)}</strong></div>`:''}${id!=='calf'&&a.variants.length?`<details><summary>查看不同难度／方向</summary><div class="chips">${a.variants.map(x=>`<span>${esc(x)}</span>`).join('')}</div><p>仅选择已确认适合的版本，不因完成次数自动进阶。</p></details>`:''}<h2>怎么做</h2><ol class="steps">${a.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><details class="precautions"><summary>开始前与停止条件</summary><p>${esc(a.note)}</p></details>${a.restricted?note('这项内容需要已有专业指导。视频未提供前，不凭文字自行学习新技术；暂不开放跟练计时。'):''}${!a.restricted&&a.timer?`<section id="timerPanel"><button class="primary" id="prepare">开始计时</button></section>`:''}${!['calf','seated','band'].includes(id)?`<section class="feedback"><h2>练习后感觉怎样？</h2><div class="feedback-row"><button data-feedback="更舒服">更舒服</button><button data-feedback="差不多">差不多</button><button data-feedback="更不舒服">更不舒服</button></div><p id="feedbackStatus" role="status" class="quiet"></p></section>`:''}`;}
function renderQuick(){root.innerHTML=back('pre','比赛／训练前')+heading('快速伤处检查','观察即可，不用反复按压或测试。')+`<form id="quickForm">${['新出现发红','新出现淤青','肿胀明显增加'].map((s,i)=>`<fieldset><legend>${s}？</legend><div class="choice">${['有','没有','不确定'].map(v=>`<label><input type="radio" required name="q${i}" value="${v}" ${quick['q'+i]===v?'checked':''}>${v}</label>`).join('')}</div></fieldset>`).join('')}<button class="primary">查看提示</button></form><div id="quickResult" role="status"></div>`;}
const urgentLabels=['明显变形或骨外露','大量或难以控制的出血','脚明显发冷、发白或发青','新出现持续麻木或脚趾不能正常活动','疼痛剧烈或迅速加重','无法负重或走几步'];
function urgentLevel(values){if(values.slice(0,5).includes('有'))return 'emergency';if(values.includes('有')||values.includes('不确定'))return 'assess';return 'care';}
function renderUrgent(){root.innerHTML=back('emergency','紧急处理')+heading('紧急情况检查','按已有观察回答，不要为了回答强行走路。')+`<form id="urgentForm">${urgentLabels.map((s,i)=>`<fieldset><legend>${esc(s)}？</legend><div class="choice">${['有','没有','不确定'].map(v=>`<label><input type="radio" required name="u${i}" value="${v}" ${urgent['u'+i]===v?'checked':''}>${v}</label>`).join('')}</div></fieldset>`).join('')}<button class="primary">查看处理提示</button></form><div id="urgentResult" role="alert" tabindex="-1"></div>`;}
function safetyForm(){const el=document.getElementById('timerPanel');el.innerHTML=`<h2>计时前确认</h2><p>请先展开并阅读本动作的“开始前与停止条件”。</p><label class="check"><input type="checkbox" id="safe">我已确认没有上述不适用情况，并遵守已有专业限制。</label><button class="primary" id="start" disabled>确认并开始</button><button class="secondary" id="cancel">暂不开始</button>`;document.querySelector('.precautions').open=true;document.getElementById('safe').onchange=e=>document.getElementById('start').disabled=!e.target.checked;document.getElementById('cancel').onclick=route;document.getElementById('start').onclick=()=>{if(!document.getElementById('safe').checked)return;guard=true;startTimer();};}
function startTimer(){if(!guard)return;const a=items[lastPath.split('/')[1]];let remaining=a.timer;timer={remaining,deadline:Date.now()+remaining*1000,running:true,checkAt:remaining>300?remaining-300:-1,checking:false};document.getElementById('timerPanel').innerHTML='<div class="clock" id="clock" role="timer"></div><p id="timerNote" role="status"></p><div class="feedback-row"><button id="pause">暂停</button><button id="end">结束</button></div>';document.getElementById('pause').onclick=()=>{if(!timer)return;if(timer.checking){timer.checking=false;document.getElementById('timerNote').textContent='已确认无异常；继续。';}timer.running=!timer.running;timer.deadline=Date.now()+timer.remaining*1000;document.getElementById('pause').textContent=timer.running?'暂停':'继续';};document.getElementById('end').onclick=()=>{stopTimer();document.getElementById('timerPanel').innerHTML=note('已结束。请记录感受，不必做满时间。');};ticker=setInterval(tick,250);tick();}
function tick(){if(!timer)return;if(timer.running)timer.remaining=Math.max(0,Math.ceil((timer.deadline-Date.now())/1000));if(timer.checkAt>=0&&timer.remaining<=timer.checkAt){timer.running=false;timer.checking=true;timer.checkAt=-1;document.getElementById('timerNote').textContent='请先取下敷物检查皮肤。有异常立即结束；无异常再继续。';document.getElementById('pause').textContent='皮肤无异常，继续';}document.getElementById('clock').textContent=String(Math.floor(timer.remaining/60)).padStart(2,'0')+':'+String(timer.remaining%60).padStart(2,'0');if(timer.remaining===0){stopTimer();document.getElementById('timerNote').textContent='本次计时结束，请移开敷物或停止练习并记录感受。';document.getElementById('pause').disabled=true;}}
function bind(){
 root.querySelectorAll('[data-calf-version]').forEach(b=>b.onclick=()=>{calfVersion=Number(b.dataset.calfVersion);renderAction('calf',lastPath.split('/')[2]);bind();root.querySelectorAll('[data-calf-version]')[calfVersion].focus();});
 const prepare=document.getElementById('prepare');if(prepare)prepare.onclick=safetyForm;
 root.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>{const title=items[lastPath.split('/')[1]].title;entries.push({title,feedback:b.dataset.feedback,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});document.getElementById('feedbackStatus').textContent=b.dataset.feedback==='更不舒服'?'请停止本次处理。持续加重或影响走路时寻求专业评估。':'已记录在本次页面中，未同步到账户。';if(b.dataset.feedback==='更不舒服'){stopTimer();const p=document.getElementById('timerPanel');if(p)p.innerHTML=note('已停止计时。');}root.querySelectorAll('[data-feedback]').forEach(x=>x.disabled=true);});
 const q=document.getElementById('quickForm');if(q)q.onsubmit=e=>{e.preventDefault();quick=Object.fromEntries(new FormData(q));const changed=Object.values(quick).some(v=>v!=='没有');document.getElementById('quickResult').innerHTML=note(changed?'新的、加重或不确定的变化值得评估。不要仅靠赛前准备判断能否运动。':'本次外观检查未报告新变化，不代表获准上场。',changed)+(changed?link('emergency','查看紧急处理'):link('pre','返回赛前准备'));};
 const u=document.getElementById('urgentForm');if(u)u.onsubmit=e=>{e.preventDefault();urgent=Object.fromEntries(new FormData(u));const level=urgentLevel(urgentLabels.map((_,i)=>urgent['u'+i]));const el=document.getElementById('urgentResult');el.innerHTML=level==='emergency'?`<div class="notice danger"><h2>暂停操作，立即寻求急救／急诊帮助</h2><p>这些表现可能涉及骨折、脱位或血管神经损伤，不能只按普通扭伤处理。请让身边的人协助联系当地急救服务，不要独自走路去就医，也不要等护理完成。</p><p>保持伤处原位，不自行掰正。大量出血用干净敷料持续按压；不要压在突出的骨头或嵌入物上，不推回或拔出。</p></div>`:level==='assess'?note('请尽快接受医疗评估，无法负重时最好当天就医。无法判断的情况先联系医疗人员，不反复试走，也不按普通扭伤自行处理。',true):note('暂未报告上述紧急表现，但不能排除骨折等损伤。症状持续或加重时仍需评估。')+link('emergency','查看适用时的护理');el.focus();el.scrollIntoView({behavior:'smooth',block:'start'});};if(u)u.onchange=()=>{const data=new FormData(u);if(urgentLabels.slice(0,5).some((_,i)=>data.get('u'+i)==='有'))u.onsubmit({preventDefault(){}});};
}
window.PainmapCare={urgentLevel};window.addEventListener('hashchange',()=>{guard=false;route();});route();
})();
