/* Foot picker: anatomical surface model; original scoring tokens are unchanged. */
(function(root){
'use strict';
const VERSION='20261001';
const ZONES=[
 ['外侧','前下','外踝前下方','Front / below outer ankle'],['外侧','中下','外踝正下方','Below outer ankle'],['外侧','后下','外踝后下方','Behind / below outer ankle'],
 ['内侧','前下','内踝前下方','Front / below inner ankle'],['内侧','中下','内踝正下方','Below inner ankle'],['内侧','后下','内踝后下方','Behind / below inner ankle'],['内侧','舟骨区','内侧舟骨区','Inner midfoot / navicular'],
 ['前方','踝前','踝关节前方','Front of ankle'],['前方','中足','足背中足','Top of midfoot'],['后方','跟腱区','跟腱区域','Achilles region'],['后方','后跟','后跟后方','Back of heel'],
 ['足底','前足','足底前足','Ball of foot'],['足底','中足','足底中足','Middle of sole'],['足底','足弓','足底足弓','Arch of sole'],['足底','后跟内侧','足底后跟内侧','Inner plantar heel'],
 ['外侧足部','第五跖骨基底','第五跖骨基底','Base of fifth metatarsal'],['外侧足部','外侧中足','外侧中足','Outer midfoot'],
 ['踝关节','内侧关节线','踝关节内侧关节线','Inner ankle joint line'],['踝关节','关节深层','踝关节深层','Deep inside ankle'],['踝关节','外侧关节线','踝关节外侧关节线','Outer ankle joint line'],
 ['踝上方','踝上','踝关节上方','Above ankle'],['大脚趾','跖趾关节','大脚趾根部关节','Big-toe base joint'],['大脚趾','第一跖骨区','第一跖骨区域','First metatarsal region']
];
function classify(x,y,z,ny,deep){
 if(deep)return y>1.55&&y<3.08&&z>-.9&&z<.85?(x>.32?17:x<-.32?19:18):-1;
 if(y>3.1)return 20;
 if(z>4.05||(z>3.55&&x<.35))return -1;
 if(ny<-.50||y<.86){if(z>2.20)return 11;if(z<.05)return x>-.10?14:-1;return x>.10?13:12;}
 if(z<-.65&&y>1.6)return 9;
 if(y>1.52&&z<.85){if(x<-.32)return z>.14?0:z<-.35?2:1;if(x>.32)return z>.14?3:z<-.35?5:4;return z<-.20?9:7;}
 if(z<-.10)return 10;
 if(x>.35&&z>2.95)return 21;
 if(x>.43&&z>1.7)return 22;
 if(x>.48&&z>.50&&z<1.7)return 6;
 if(x<-.62&&z>.55&&z<2.50)return z<1.40?15:16;
 if(y>1.7&&z<1.30)return 7;
 if(x>.30&&y<1.13&&z<1.8)return 13;
 return 8;
}
const jobs={};function load(src,ready){if(ready())return Promise.resolve();if(jobs[src])return jobs[src];jobs[src]=new Promise((resolve,reject)=>{const script=document.createElement('script');const timeout=setTimeout(()=>reject(new Error('timeout')),20000);script.src=src;script.onload=()=>{clearTimeout(timeout);ready()?resolve():reject(new Error('missing asset'));};script.onerror=()=>{clearTimeout(timeout);reject(new Error('asset unavailable'));};document.head.append(script);}).catch(e=>{delete jobs[src];throw e;});return jobs[src];}
function mount(container,{answers={},language='zh',onChange=()=>{}}={}){
 const en=language==='en',t=(zh,eng)=>en?eng:zh,label=id=>ZONES[id]?.[en?3:2]||t('未覆盖的区域','Area not covered');
 let disposed=false,selected=ZONES.findIndex(z=>z[0]===answers.primary_location&&z[1]===answers.secondary_location),side=answers.foot_side==='left'?'left':'right',deep=selected>=17&&selected<=19,hover=-1,yaw=-.95,pitch=.32,zoom=1,renderer,geometry,material,texture,capGeometry,capMaterial,resizeObserver,paint=()=>{},draw=()=>{},pick=()=>-1,pointers=new Map(),gesture=null,pinching=false,lastSource='3d';
 const $=s=>container.querySelector(s);container.className='pm3d';
 container.innerHTML=`<style>
 .pm3d{--pm-surface:#f4f7f6;--pm-line:#d4e2e0;--pm-ink:#173c40;--pm-soft:#526e72;color:var(--pm-ink)}.pm3d *{box-sizing:border-box}.pm3d .pm-toolbar{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.pm3d button,.pm3d select{font:inherit;color:var(--pm-ink);background:#fff;border:1px solid var(--pm-line);border-radius:9px;padding:9px 12px;min-height:44px}.pm3d button{cursor:pointer}.pm3d button[aria-pressed=true]{background:#167e83;color:#fff;border-color:#167e83}.pm3d .pm-spacer{flex:1}.pm3d .pm-stage{position:relative;height:470px;background:radial-gradient(ellipse at 50% 65%,#dce8e5,#f6f9f8 70%);border:1px solid var(--pm-line);border-radius:16px;overflow:hidden;touch-action:none}.pm3d canvas{display:block;width:100%;height:100%;cursor:grab}.pm3d .pm-badge{position:absolute;top:12px;left:12px;right:12px;width:fit-content;max-width:calc(100% - 24px);background:rgba(255,255,255,.94);border:1px solid var(--pm-line);padding:7px 11px;border-radius:8px;font-size:13px;pointer-events:none}.pm3d .pm-navigation{position:absolute;bottom:12px;right:12px;display:flex;gap:6px}.pm3d .pm-navigation button{padding:7px 11px}.pm3d .pm-caption{font-size:13px;color:var(--pm-soft);margin:8px 0 14px}.pm3d .pm-selection{padding:14px 16px;background:#edf5f3;border-radius:10px;border-left:3px solid #16858b;margin:12px 0;font-weight:600}.pm3d .pm-select{width:100%;max-width:100%;font-size:16px;margin:8px 0}.pm3d details{margin-top:12px}.pm3d summary{cursor:pointer}.pm3d .pm-error{color:#8c3c20;margin:8px 0}.pm3d .pm-deep{margin:10px 0;display:flex;gap:6px;flex-wrap:wrap}.pm3d .pm-attribution{font-size:12px;color:var(--pm-soft);margin:10px 0 0}.pm3d .pm-attribution a{color:inherit}.pm3d .pm-status{font-size:13px;min-height:1.5em;margin-top:6px}.pm3d .pm-deep[hidden]{display:none}@media(max-width:480px){.pm3d .pm-stage{height:405px}.pm3d .pm-spacer{display:none}.pm3d .pm-toolbar{gap:5px}.pm3d button{padding:8px 10px}}
 </style>
 <div class="pm-toolbar" aria-label="${t('左右脚与视角','Foot and view')}"><button type="button" data-side="right">${t('右脚','Right foot')}</button><button type="button" data-side="left">${t('左脚','Left foot')}</button><span class="pm-spacer"></span>${[['outer','外侧','Outer'],['inner','内侧','Inner'],['front','足背','Top'],['back','后方','Back'],['sole','足底','Sole']].map(([v,zh,eng])=>`<button type="button" data-view="${v}">${t(zh,eng)}</button>`).join('')}</div>
 <div class="pm-toolbar" aria-label="${t('定位方式','Location mode')}"><button type="button" data-mode="surface">${t('表面位置','Surface location')}</button><button type="button" data-mode="deep">${t('踝关节内部','Inside ankle joint')}</button></div>
 <div class="pm-stage"><span class="pm-badge">${t('正在加载足部模型…可先从下方列表选位置。','Loading foot… You can use the location list below.')}</span><div class="pm-navigation"><button type="button" data-zoom="in" aria-label="${t('放大','Zoom in')}">＋</button><button type="button" data-zoom="out" aria-label="${t('缩小','Zoom out')}">−</button><button type="button" data-view="default">${t('复位','Reset view')}</button></div></div>
 <p class="pm-caption">${t('拖动旋转，移到区域时高亮，点击选中。手机可双指缩放。','Drag to rotate, hover to highlight, tap to select. Pinch to zoom on a phone.')}</p>
 <div class="pm-deep" hidden>${[17,18,19].map(i=>`<button type="button" data-joint="${i}">${label(i)}</button>`).join('')}</div>
 <div class="pm-selection" aria-live="polite"></div><div class="pm-status" role="status"></div>
 <details class="pm-list"><summary>${t('按名称选择／模型无法显示','Choose by name / model unavailable')}</summary><label>${t('疼痛最明显的位置','Most painful location')}<select class="pm-select"><option value="">${t('请选择位置','Choose a location')}</option>${ZONES.map((z,i)=>`<option value="${i}">${label(i)}</option>`).join('')}</select></label></details>
 <p class="pm-attribution">${t('足部外形仅用于定位，不代表个人解剖或诊断。','Foot shape is for location selection, not individual anatomy or diagnosis.')} <a href="FOOT_MODEL_CREDITS.md" target="_blank" rel="noopener">${t('模型来源','Model credits')}</a></p>`;
 const stage=$('.pm-stage'),badge=$('.pm-badge'),select=$('select'),status=$('.pm-status');
 function sync(){container.querySelectorAll('[data-side]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.side===side)));container.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String((b.dataset.mode==='deep')===deep)));container.querySelectorAll('[data-joint]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.joint===selected)));$('.pm-deep').hidden=!deep;select.value=selected<0?'':String(selected);$('.pm-selection').textContent=selected<0?t('尚未选择疼痛位置','No location selected'):(side==='right'?t('右脚','Right foot'):t('左脚','Left foot'))+' · '+label(selected);}
 function notify(){const z=ZONES[selected];onChange(z?{primary_location:z[0],secondary_location:z[1],foot_side:side,location_input:lastSource,location_model_version:VERSION}:null);}
 function choose(id,source='3d'){selected=id;lastSource=source;deep=id>=17&&id<=19;hover=-1;status.textContent='';sync();paint();notify();}
 select.onchange=()=>choose(select.value===''?-1:Number(select.value),'list');
 container.querySelectorAll('[data-joint]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.joint),'joint-choice'));
 container.querySelectorAll('[data-side]').forEach(b=>b.onclick=()=>{side=b.dataset.side;hover=-1;sync();paint();notify();});
 container.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{const next=b.dataset.mode==='deep';if(next===deep)return;deep=next;selected=-1;hover=-1;sync();paint();notify();status.textContent=deep?t('关节内部无法直接从皮肤看到，请选择最接近的关节位置。','The joint interior is not visible through the skin. Choose the closest joint location.'):'';});
 container.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const s=side==='right'?1:-1;const views={outer:[-Math.PI/2*s,.12],inner:[Math.PI/2*s,.12],front:[0,.86],back:[Math.PI,.15],sole:[0,-1.48],default:[-.95*s,.32]};[yaw,pitch]=views[b.dataset.view];if(b.dataset.view==='default')zoom=1;hover=-1;paint();});
 container.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{zoom=Math.max(.75,Math.min(2,zoom*(b.dataset.zoom==='in'?1.15:1/1.15)));draw();});sync();
 Promise.all([load('js/three.min.js?v=128',()=>!!root.THREE),load('js/foot-model.js?v='+VERSION,()=>!!root.PainmapFootModel)]).then(()=>{
  if(disposed)return;const THREE=root.THREE,data=root.PainmapFootModel;
  renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(root.devicePixelRatio||1,2));renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;const canvas=renderer.domElement;stage.prepend(canvas);canvas.setAttribute('role','img');canvas.setAttribute('aria-label',t('可旋转与点选的足踝模型；下方可按名称选择。','Rotatable foot model. A keyboard-accessible location list is below.'));
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,100),target=new THREE.Vector3(0,3.0,1.30),ray=new THREE.Raycaster(),mouse=new THREE.Vector2();scene.add(new THREE.HemisphereLight(0xfff6ed,0x75847e,.95));const key=new THREE.DirectionalLight(0xfff4e9,1.2);key.position.set(-4,8,6);scene.add(key);const fill=new THREE.DirectionalLight(0xe6f1ff,.6);fill.position.set(5,4,-4);scene.add(fill);
  const indexed=new THREE.BufferGeometry();indexed.setAttribute('position',new THREE.Float32BufferAttribute(data.positions,3));indexed.setAttribute('normal',new THREE.Float32BufferAttribute(data.normals,3));indexed.setAttribute('uv',new THREE.Float32BufferAttribute(data.uv,2));indexed.setIndex(data.indices);geometry=indexed.toNonIndexed();indexed.dispose();const pos=geometry.attributes.position,norm=geometry.attributes.normal,colors=new Float32Array(pos.count*3),surface=[],joints=[];geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));
  for(let f=0;f<pos.count/3;f++){let x=0,y=0,z=0,ny=0;for(let k=0;k<3;k++){const i=f*3+k;x+=pos.getX(i)/3;y+=pos.getY(i)/3;z+=pos.getZ(i)/3;ny+=norm.getY(i)/3;}surface.push(classify(x,y,z,ny,false));joints.push(classify(x,y,z,ny,true));}
  texture=new THREE.TextureLoader().load(data.texture,()=>{if(disposed){texture.dispose();return;}draw();},undefined,()=>{if(!disposed)badge.textContent=t('材质未加载，仍可选择区域','Texture unavailable; location selection still works');});texture.encoding=THREE.sRGBEncoding;texture.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());material=new THREE.MeshStandardMaterial({map:texture,vertexColors:true,roughness:.68,metalness:0});const foot=new THREE.Mesh(geometry,material);scene.add(foot);
  draw=()=>{if(disposed)return;const distance=stage.clientWidth<430?15.6:13.1;camera.position.set(target.x+distance*Math.cos(pitch)*Math.sin(yaw),target.y+distance*Math.sin(pitch),target.z+distance*Math.cos(pitch)*Math.cos(yaw));camera.zoom=zoom;camera.updateProjectionMatrix();camera.lookAt(target);renderer.render(scene,camera);};
  paint=()=>{if(disposed)return;const white=new THREE.Color(0xffffff),active=new THREE.Color(0x28b3c0),over=new THREE.Color(0x7de0dc);const zones=deep?joints:surface;for(let f=0;f<zones.length;f++){const id=zones[f],c=id>=0&&id===selected?active:id>=0&&id===hover?over:white;for(let k=0;k<3;k++)c.toArray(colors,(f*3+k)*3);}geometry.attributes.color.needsUpdate=true;foot.scale.x=side==='right'?1:-1;badge.textContent=hover>=0?label(hover)+t(' · 点击选择',' · click to select'):selected>=0?t('已选：','Selected: ')+label(selected):deep?t('选择踝关节位置','Choose ankle joint location'):t('移到疼痛区域，再点击','Hover over the painful area, then click');draw();};
  function resize(){if(disposed)return;const w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;draw();}resizeObserver=new ResizeObserver(resize);resizeObserver.observe(stage);
  pick=e=>{const r=canvas.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);const h=ray.intersectObject(foot)[0];return h?(deep?joints:surface)[h.faceIndex]:-2;};
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);if(pointers.size===1){gesture={x:e.clientX,y:e.clientY,yaw,pitch,moved:false};pinching=false;}else{const [a,b]=[...pointers.values()];gesture={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom};pinching=true;}});
  canvas.addEventListener('pointermove',e=>{if(pointers.has(e.pointerId)){pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){const [a,b]=[...pointers.values()];zoom=Math.max(.75,Math.min(2,gesture.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,gesture.distance)));draw();return;}if(pinching||!gesture)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)>5)gesture.moved=true;if(gesture.moved){yaw=gesture.yaw-dx*.008;pitch=Math.max(-1.50,Math.min(1.50,gesture.pitch+dy*.007));hover=-1;draw();}return;}const h=pick(e),id=h>=0?h:-1;if(id!==hover){hover=id;paint();}});
  canvas.addEventListener('pointerup',e=>{if(!pointers.has(e.pointerId))return;const wasPinch=pinching;pointers.delete(e.pointerId);if(!wasPinch&&gesture&&!gesture.moved){const h=pick(e);if(h>=0)choose(h);else if(h===-1){selected=-1;hover=-1;sync();paint();notify();status.textContent=t('这处表面暂未覆盖。请按名称核对位置，不要勉强选择相邻区域。','This surface is not covered. Check the location list; do not choose an unrelated area.');}}if(!pointers.size){gesture=null;pinching=false;}});
  canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);if(!pointers.size){gesture=null;pinching=false;}});canvas.addEventListener('pointerleave',()=>{if(!pointers.size){hover=-1;paint();}});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.75,Math.min(2,zoom-e.deltaY*.001));draw();},{passive:false});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('.pm-list').open=true;badge.textContent=t('三维显示已暂停，请使用下方位置列表。','3D display paused. Please use the location list.');});resize();paint();
 }).catch(()=>{if(disposed)return;$('.pm-list').open=true;badge.textContent=t('三维模型暂时无法加载，请使用下方位置列表。','3D model unavailable. Please use the location list below.');});
 return {dispose(){disposed=true;resizeObserver?.disconnect();geometry?.dispose();material?.dispose();texture?.dispose();capGeometry?.dispose();capMaterial?.dispose();renderer?.dispose();},getSelection(){return selected>=0?{zone:selected,side}:null;}};
}
root.PainmapLocation3D={mount,zones:ZONES,classify,version:VERSION};
})(window);
