// Logic-tree explorer: live scoring data; no screening submissions.
(function(){
function conditionSetForMode(mode) {
  if (mode === "acute") return ACUTE_CONDITIONS;
  if (mode === "chronic") return CHRONIC_CONDITIONS;

  // An uncertain onset must not be silently classified as overuse. Keep both
  // libraries eligible, merging the few shared diagnoses into one candidate.
  const combined = {};
  [ACUTE_CONDITIONS, CHRONIC_CONDITIONS].forEach((library) => {
    Object.entries(library).forEach(([key, condition]) => {
      if (!combined[key]) {
        combined[key] = { ...condition, rules: [...(condition.rules || [])] };
        return;
      }
      combined[key] = {
        ...combined[key],
        ...condition,
        rules: [...(combined[key].rules || []), ...(condition.rules || [])],
      };
    });
  });
  return combined;
}

function recommendationText(ranking) {
  const top = ranking[0];
  if (!top) {
    return { urgent: false, text: uiText("No strong high-risk pattern was identified. Monitor your symptoms and seek a sports-medicine or orthopedic assessment if pain persists beyond one week, worsens, or is accompanied by swelling or instability.", "目前没有发现明显的高风险模式。请继续观察；如果疼痛超过一周、逐渐加重，或伴随肿胀和不稳定，应接受运动医学或骨科评估。") };
  }
  if (top.scorePct >= 70 && /fracture|骨折|Lisfranc/i.test(top.key + top.category)) {
    return { urgent: true, text: uiText(`Your answers are consistent with ${top.nameEn}. Because a fracture or major structural injury is possible, seek prompt medical assessment and appropriate imaging. Avoid weight-bearing training until cleared.`, `你的答案与${top.nameZh}较为一致。由于可能存在骨折或严重结构损伤，请尽快接受医疗评估和适当影像检查；在获准前避免负重训练。`) };
  }
  if (top.scorePct >= 70) {
    return { urgent: false, text: uiText(`Your answers most closely match ${top.nameEn}. Reduce painful movements and training load, and arrange a sports-medicine or orthopedic assessment. The suggested tests below can support that clinical evaluation.`, `你的答案与${top.nameZh}最为接近。请减少引起疼痛的动作和训练负荷，并安排运动医学或骨科评估；下方建议检查可为临床评估提供参考。`) };
  }
  return { urgent: false, text: uiText("The pattern is not highly specific and may fit several conditions. Review the top possibilities with a clinician or qualified team medical professional before returning to full training.", "当前症状模式不够特异，可能符合多种伤病。在恢复完整训练前，请与医生或合格队医一起评估排名靠前的可能伤病。") };
}

const root=document.getElementById('painmap-logic');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>root.querySelector(s);const modes={acute:'明确的一次受伤',chronic:'逐渐出现／劳损',unknown:'不知道／不确定'};
const labels={...Object.fromEntries([...ACUTE_QUESTIONS,...CHRONIC_QUESTIONS,...ADDITIONAL_QUESTIONS,...YESNO_QUESTIONS,...FUNCTIONAL_TESTS].map(q=>[q.field,q.title])),primary_location:'主要疼痛位置',secondary_location:'具体疼痛位置',pain_shape:'疼痛形状',pain_depth:'疼痛深度',standing_pain:'站着不动会痛吗？',onset_event:'起病方式'};
const initial={vas:3,unable_to_weight_bear:false,deformity:false,severe_rest_pain:false,night_pain:false,neurological_symptoms:false,onset_event:'acute',mechanism:'内翻',contact:'垫脚',immediate_function:'能走不能跑',injury_sensation:'啪',pain_action:'变向',primary_location:'外侧',secondary_location:'前下',pain_shape:'点',pain_depth:'表浅',activity_pattern:'越动越痛',pain_pattern:'只有运动',specific_trigger:'变向',swelling_severity:'轻度',swelling_timing:'数小时',bruising:'轻度',inflammation_heat:'否',instability:'是',recurrent_sprain:'否',single_leg_stand:'正常',single_leg_hop:'正常',change_direction_test:'正常',push_off_test:'正常'};
let answers={...initial},tests={},view='tree',selected='',lastField='mechanism',openGroups=new Set(['route','history']);
const uiText=(en,zh)=>zh;
function emergency(a){return PainmapTriage.evaluate(a).level!=='continue';}
function run(a=answers,t=tests){const mode=a.onset_event,set=conditionSetForMode(mode),base=computeBaseScores(set,a,mode);if(mode==='acute')applyOverrides(base.scores,a,ACUTE_OVERRIDES,base.supporting);const prelim=rankConditions(base.scores,set,3,base.locationScores,base.evidenceEligibility);const permitted=Object.fromEntries(prelim.map(r=>[r.key,t[r.key]||{}]));const final={...base.scores};applyTestAdjustments(final,permitted);return {set,base,final,prelim,ranking:rankConditions(final,set,3,base.locationScores,base.evidenceEligibility),emergency:emergency(a)};}
function locationKeys(mode,p,s){const set=conditionSetForMode(mode);return Object.entries(set).filter(([k,c])=>!c.hidden&&locationEligibilityMatches({primary_location:p},c)&&c.rules.some(r=>r.when.some(w=>w.field==='primary_location'||w.field==='secondary_location')&&ruleHits({primary_location:p,secondary_location:s},r)&&r.points>0)).map(([k,c])=>({key:k,name:c.nameZh}));}
function save(){try{sessionStorage.setItem('painmap.logic-tree.v1',JSON.stringify({modelContent:{view,selectedCondition:selected},privateContent:{answers,tests,lastField,openGroups:[...openGroups]}}));}catch{}}
function restore(w){if(!w)return;const p=w.privateContent;if(p?.answers&&modes[p.answers.onset_event]){answers=p.answers;tests=p.tests||{};lastField=p.lastField||'mechanism';openGroups=new Set(p.openGroups||['route']);}view=w.modelContent?.view==='simulate'?'simulate':'tree';selected=w.modelContent?.selectedCondition||'';}
function renderTree(){let s='<ul class="tree-list"><li><strong>当前情况 → 红旗追问 → 立即就医／尽快评估／继续问卷</strong><ul class="tree-list">';for(const [mode,title] of Object.entries(modes)){s+=`<li><details ${mode==='acute'?'open':''}><summary>${title} → ${mode==='unknown'?'合并急性与劳损伤病库':mode==='acute'?'急性伤病库':'劳损伤病库'}</summary><ul class="tree-list">`;for(const [p,subs] of Object.entries(PAIN_MAP_REGIONS)){s+=`<li><details ${mode==='acute'&&p==='外侧'?'open':''}><summary>${p}</summary><ul class="tree-list">`;for(const sub of subs){const ks=locationKeys(mode,p,sub);s+=`<li><div class="leaf"><button class="btn" data-path="${esc([mode,p,sub].join('|'))}">${sub} →</button><div class="leaf-output">${ks.length?ks.map(x=>esc(x.name)).join(' ／ '):'<span class="coverage">无位置计分覆盖 → 无候选</span>'}<small>${ks.length?'仅有位置资格；继续选症状才能判断是否过门槛':''}</small></div></div></li>`;}s+='</ul></details></li>';}s+='</ul></details></li>';}$('#branch-tree').innerHTML=s+'</ul></li></ul>';}
function field(q){const a=answers[q.field];if(q.multi)return `<div><span>${q.title}</span><div class="option-checks">${q.options.map(o=>`<label class="form-check"><input class="form-check-input" type="checkbox" data-multi="${q.field}" value="${esc(o.v)}" ${Array.isArray(a)&&a.includes(o.v)?'checked':''}><span class="form-check-label">${o.label}</span></label>`).join('')}</div></div>`;return `<label class="form-label">${q.title}<select class="form-select" data-field="${q.field}"><option value="">未选择</option>${q.options.map(o=>`<option value="${esc(o.v)}" ${a===o.v?'selected':''}>${esc(o.label)}</option>`).join('')}</select></label>`;}
function group(id,title,body){return `<details class="editor-group" data-group="${id}" ${openGroups.has(id)?'open':''}><summary>${title}</summary><div class="fields">${body}</div></details>`;}
function renderEditor(){const mode=answers.onset_event;let s=group('danger','① 安全追问 → 分级分流',`<label class="form-label">疼痛程度（0–10）<select class="form-select" data-vas>${Array.from({length:11},(_,i)=>`<option ${Number(answers.vas)===i?'selected':''}>${i}</option>`).join('')}</select></label>${REDFLAG_OPTIONS.map(o=>`<label class="form-check"><input class="form-check-input" type="checkbox" data-flag="${o.id}" ${answers[o.id]?'checked':''}><span class="form-check-label">${o.label}</span></label>`).join('')}${PainmapTriage.active(answers).map(q=>field({field:q.field,title:q.zh,options:q.options.map(o=>({v:o.v,label:o.zh}))})).join('')}`);
s+=group('route','② 起病＋位置 → 候选范围',field({field:'onset_event',title:'起病方式',options:Object.entries(modes).map(([v,label])=>({v,label}))})+field({field:'primary_location',title:'主要疼痛区域',options:Object.keys(PAIN_MAP_REGIONS).map(v=>({v,label:v}))})+field({field:'secondary_location',title:'具体疼痛位置',options:(PAIN_MAP_REGIONS[answers.primary_location]||[]).map(v=>({v,label:v}))}));
let qs=mode==='acute'?ACUTE_QUESTIONS:CHRONIC_QUESTIONS;let hs=qs.map(field).join('');if(mode!=='acute'&&answers.pain_action==='静止休息')hs+=field({field:'standing_pain',title:'站着不动会痛吗？',options:STANDING_PAIN_OPTIONS});if(mode==='unknown')hs+='<span class="text-small text-muted">不确定分支使用劳损问卷，评分时合并两类伤病。</span>';s+=group('history','③ 病史选择 → 特征加分',hs);
s+=group('symptoms','④ 疼痛与症状 → 特征加分',[{field:'pain_shape',title:'疼痛形状',options:PAIN_SHAPE_OPTIONS},{field:'pain_depth',title:'疼痛深度',options:PAIN_DEPTH_OPTIONS},...ADDITIONAL_QUESTIONS.filter(q=>!q.skipIf?.(answers)),...YESNO_QUESTIONS.filter(q=>!q.onlyFor||q.onlyFor===mode)].map(field).join(''));
s+=group('function','⑤ 功能测试 → 特征加分',FUNCTIONAL_TESTS.map(field).join(''));$('#answer-editor').innerHTML=s;}
function gates(k,b){return [[b.locationScores[k]>0,`位置分 > 0：${(b.locationScores[k]||0).toFixed(1)}`],[b.otherScores[k]>=15,`其他特征分 ≥ 15：${(b.otherScores[k]||0).toFixed(1)}`],[b.otherFieldCounts[k]>=2,`非位置字段 ≥ 2：${b.otherFieldCounts[k]||0}`],[b.scores[k]>=35,`基础总分 ≥ 35：${(b.scores[k]||0).toFixed(1)}`]];}
function renderOutput(){const r=run();$('#path-label').innerHTML=`<span>${esc(modes[answers.onset_event])}</span><span>→</span><span>${esc(answers.primary_location||'未选位置')} · ${esc(answers.secondary_location||'未选具体位置')}</span><span>→</span><span>${r.emergency?'中止':r.ranking.length+'个最终候选'}</span>`;if(r.emergency){const triage=PainmapTriage.evaluate(answers);$('#live-output').innerHTML=`<h3>高风险信号 → ${triage.level==='immediate'?'立即就医':'尽快接受专业评估'}</h3><ul>${triage.reasons.map(r=>`<li>${esc(r.zh)}</li>`).join('')}</ul><p>不输出伤病排名或动作测试；可以整理就医摘要。</p><small>未选择的红旗追问按保守方式分流。正式问卷要求先填写追问。</small>`;$('#condition-detail').innerHTML='';return;}
const entries=Object.entries(r.base.scores).filter(([k])=>!r.set[k].hidden).sort((a,b)=>b[1]-a[1]);if(!entries.some(([k])=>k===selected))selected=r.ranking[0]?.key||entries[0]?.[0]||'';
let out='<div class="viz-row text-small"><span><i class="dot"></i>位置分／40</span><span><i class="dot other"></i>其他特征／60</span></div>';
if(!r.ranking.length)out+='<h3>没有伤病达到最低证据门槛</h3>';
for(const x of r.ranking){out+=`<div class="candidate"><div class="candidate-head"><button class="btn" data-condition="${x.key}" aria-pressed="${selected===x.key}">${r.ranking.indexOf(x)+1}. ${esc(x.nameZh)}</button><strong class="tabular-nums">${x.score} 分</strong></div><div class="score-track" aria-label="基础分组成"><span class="location-mark" style="width:${r.base.locationScores[x.key]}%"></span><span class="other-mark" style="width:${r.base.otherScores[x.key]}%"></span></div><small>基础 ${r.base.scores[x.key].toFixed(1)} → 特殊检查后 ${x.score}</small></div>`;}
const failed=entries.filter(([k])=>!r.ranking.some(x=>x.key===k));out+=`<details><summary>查看其余计分对象（${failed.length}）</summary>${failed.map(([k,v])=>`<div class="candidate-head"><button class="btn btn-ghost" data-condition="${k}">${esc(r.set[k].nameZh)}</button><span class="text-small">${r.base.evidenceEligibility[k]?'已过门槛，未入前3名':gates(k,r.base).filter(g=>!g[0]).map(g=>g[1].split('：')[0]+' 未满足').join('；')}</span></div>`).join('')||'无'}</details>`;
const excluded=Object.entries(r.set).filter(([k,c])=>!c.hidden&&!(k in r.base.scores));out+=`<details><summary>主要位置排除的伤病（${excluded.length}）</summary><div class="text-small">${excluded.map(([k,c])=>esc(c.nameZh)).join('、')||'无'}</div></details>`;
out+='<hr><strong>结果页的下一步建议</strong><p>'+esc(recommendationText(r.ranking).text)+'</p>';$('#live-output').innerHTML=out;renderDetail(r);}
function allRules(r,k){return [...r.set[k].rules,...buildGlobalRules(answers.onset_event).flatMap(g=>g.effects.filter(e=>e.key===k).map(e=>({points:e.points,when:g.conditions})))];}
function readableRule(rule){return rule.when.map(c=>`${labels[c.field]||c.field}＝${Array.isArray(c.match)?c.match.join('／'):c.match}`).join(' 且 ');}
function renderDetail(r){if(!selected||!r.set[selected]){$('#condition-detail').innerHTML='';return;}const k=selected,b=r.base,cond=r.set[k];const hits=allRules(r,k).filter(rule=>ruleHits(answers,rule));let s=`<hr><h3>${esc(cond.nameZh)} · 为什么出现／没有出现</h3><div class="rule-columns"><div><strong>累计得分 → 四个条件同时满足</strong><div class="gates">${gates(k,b).map(([ok,label])=>`<span>${ok?'✓':'未通过 ·'} ${label}</span>`).join('')}</div><details><summary>命中的原始加分规则（${hits.length}）</summary><table class="table table-sm"><thead><tr><th>答案条件</th><th>原始分</th></tr></thead><tbody>${hits.map(rule=>`<tr><td>${esc(readableRule(rule))}</td><td>+${rule.points}</td></tr>`).join('')}</tbody></table></details><details><summary>全部规则，包括尚未命中的条件</summary><table class="table table-sm"><thead><tr><th>条件</th><th>原始分</th><th>命中</th></tr></thead><tbody>${allRules(r,k).map(rule=>`<tr><td>${esc(readableRule(rule))}</td><td>${rule.points}</td><td>${ruleHits(answers,rule)?'✓':'—'}</td></tr>`).join('')}</tbody></table></details><small>原始分按可达最高分归一化到位置40分、其他60分。</small></div><div>`;
const isPrelim=r.prelim.some(x=>x.key===k);s+='<strong>⑥ 特殊检查 → 调整最终分</strong>';if(isPrelim){s+=`<div class="fields">${(SPECIAL_TESTS[k]||SPECIAL_TEST_FALLBACK).map(t=>`<label class="form-label">${esc(t.name)}<select class="form-select" data-test="${esc(t.name)}" data-test-key="${k}">${[['skip','未测试／不确定'],['positive','阳性：乘以1.10'],['negative','阴性：乘以0.95']].map(([v,label])=>`<option value="${v}" ${(tests[k]?.[t.name]||'skip')===v?'selected':''}>${label}</option>`).join('')}</select></label>`).join('')}</div>`;}else s+='<p>尚未进入基础排名前3名，不展示该伤病的特殊检查。</p>';s+='<small>上限100分；特殊检查不改变已计算的基础门槛资格。</small></div></div>';
const currentQ=[...ACUTE_QUESTIONS,...CHRONIC_QUESTIONS,...ADDITIONAL_QUESTIONS,...YESNO_QUESTIONS,...FUNCTIONAL_TESTS,{field:'pain_shape',title:'疼痛形状',options:PAIN_SHAPE_OPTIONS},{field:'pain_depth',title:'疼痛深度',options:PAIN_DEPTH_OPTIONS}].find(q=>q.field===lastField&&!q.multi);
if(currentQ){const unique=[...new Map(currentQ.options.map(o=>[o.v,o])).values()];s+=`<details open><summary>同一题换个答案 → ${esc(cond.nameZh)} 的变化</summary><div class="text-small">${esc(currentQ.title)} · 其余答案保持不变 · 比较基础分</div><table class="table table-sm"><thead><tr><th>选项</th><th>基础分</th><th>门槛</th></tr></thead><tbody>${unique.map(o=>{const alt={...answers,[lastField]:o.v};if(lastField==='swelling_severity'&&o.v==='无')delete alt.swelling_timing;const rr=run(alt,{});return `<tr><td>${esc(o.label)}${answers[lastField]===o.v?' ← 当前':''}</td><td class="tabular-nums">${(rr.base.scores[k]||0).toFixed(1)}</td><td>${rr.base.evidenceEligibility[k]?'通过':'未通过'}</td></tr>`;}).join('')}</tbody></table></details>`;}
const isFinal=r.ranking.some(x=>x.key===k);s+=`<details ${isFinal?'open':''}><summary>⑦ ${isFinal?'最终会显示':'当前未输出；查看配置的'}康复／训练建议</summary><div class="text-small">系统现有文案 · 关节稳定且已获医疗许可后，再考虑相应活动</div><ul>${(REHAB[k]||REHAB_FALLBACK).map(line=>`<li>${esc(line)}</li>`).join('')}</ul></details>`;$('#condition-detail').innerHTML=s;}
function render(){root.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));root.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==view);if(view==='tree')renderTree();else{renderEditor();renderOutput();}}
function changeMode(mode){answers.onset_event=mode;for(const f of ['mechanism','contact','immediate_function','injury_sensation','load_change','standing_pain','bruising','recurrent_sprain'])delete answers[f];if(mode==='acute'){for(const f of ['mechanism','contact','immediate_function','injury_sensation','bruising','recurrent_sprain'])answers[f]=initial[f];}else answers.load_change=['无变化'];tests={};selected='';}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();save();}if(b.dataset.path){const [mode,p,s]=b.dataset.path.split('|');if(mode!==answers.onset_event)changeMode(mode);answers.primary_location=p;answers.secondary_location=s;tests={};selected='';view='simulate';render();save();}if(b.dataset.condition){selected=b.dataset.condition;renderOutput();save();}});
root.addEventListener('toggle',e=>{const d=e.target;if(d.dataset?.group){if(d.open)openGroups.add(d.dataset.group);else openGroups.delete(d.dataset.group);}},true);
root.addEventListener('change',e=>{const el=e.target;if(el.dataset.test){const k=el.dataset.testKey;tests[k]??={};if(el.value==='skip')delete tests[k][el.dataset.test];else tests[k][el.dataset.test]=el.value;renderOutput();save();return;}if(el.hasAttribute('data-vas'))answers.vas=Number(el.value);else if(el.dataset.flag)answers[el.dataset.flag]=el.checked;else if(el.dataset.multi){let set=new Set(answers[el.dataset.multi]||[]);if(el.checked){if(el.value==='无变化')set=new Set();else set.delete('无变化');set.add(el.value);}else set.delete(el.value);answers[el.dataset.multi]=[...set];lastField=el.dataset.multi;}else if(el.dataset.field){const f=el.dataset.field;lastField=f;if(f==='onset_event'&&el.value)changeMode(el.value);else if(f==='onset_event')return;else if(el.value)answers[f]=el.value;else delete answers[f];if(f==='primary_location')answers.secondary_location=PAIN_MAP_REGIONS[el.value]?.[0];if(f==='swelling_severity'&&el.value==='无')delete answers.swelling_timing;if(f==='pain_action'&&el.value!=='静止休息')delete answers.standing_pain;}else return;tests={};renderEditor();renderOutput();save();});
try{restore(JSON.parse(sessionStorage.getItem('painmap.logic-tree.v1')||'null'));}catch{}
render();

})();
